# defaultContentLanguage = 'ja'
baseURL = '/ocitutorials/'
# languageCode = 'ja'
publishDir = "public/ocitutorials"
# title = 'OCIチュートリアルaaaaa'
# theme = "hugo-geekdoc"

# pluralizeListTitles = false

# Geekdoc required configuration
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# disablePathToLower = true

# Required if you want to render robots.txt template
# enableRobotsTXT = true

# enableGitInfo = true

# geekdocRepo = "https://github.com/oracle-japan/ocitutorials"

# Needed for mermaid shortcodes
# [markup]
  # [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    # unsafe = true
  # [markup.tableOfContents]
    # startLevel = 1
    # endLevel = 9

# [taxonomies]
   # tag = "tags"

# [outputs]
   # home = ["HTML"]
   # section = ["HTML"]
   # page = ["HTML"]
   # term = ["HTML"]

# [params]
  # customCSS = ["./custom.css"]
  # favicon = "./img/favicon.ico"
  # geekdocLogo = "./img/theo_white.png"
  # geekdocMenuBundle = false
  # geekdocPageLastmod = true
  # geekdocBreadcrumb = true
  # geekdocTagsToMenu = true
  # geekdocBackToTop = true                    # topへ戻るボタン
  # description = 'Oracle Cloud Infrastructureの公式チュートリアル集です。'
  # images = ['../img/hero/Infrastructure_1.png']
  # title = 'Oracle Cloud Infrastructure チュートリアル'
  # [params.social]
    # twitter = 'Oracle_Japan'

# [params.geekdocContentLicense]
  # name = "日本オラクル株式会社"
  # link = "https://www.oracle.com/jp/"

# [services]
  # [services.googleAnalytics]
    # id = 'G-6W7FEC5CEH'
