reviewers:
  defaults:
  - tniita
  - mmarukaw
  - shukawam
  - cyberblack28
  - nonkyon

files:
  'tutorials/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - gakumura
    - yoinakag
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - kyyamada
    - SNAKANE
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sesecho
    - yobaya
    - fwiw6430
    - kofukush
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '_pages/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - gakumura
    - yoinakag
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - kyyamada
    - SNAKANE
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sesecho
    - yobaya
    - fwiw6430
    - kofukush
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
  '.github/**':
    - tniita
    - mmarukaw
    - shukawam
    - cyberblack28
    - nonkyon

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3