reviewers:
  defaults:
    - tniita
    - mmarukaw
    - cyberblack28
    - nonkyon
    - sogawa-yk

files:
  "tutorials/**":
    - tniita
    - cyberblack28
    - mmarukaw
    - kenkensonson
    - YoshiakiYamasaki
    - gakumura
    - yoinakag
    - eminamin
    - TomokoKonishi
    - ora-takahnak
    - nonkyon
    - kyyamada
    - SNAKANE
    - yuarashi
    - s-nori
    - fwiw6430
    - kofukush
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - watarunS
    - ntakei1
    - unyako
    - t-utsunom
    - sogawa-yk
    - alkuma-san
  "_pages/**":
    - tniita
    - cyberblack28
    - mmarukaw
    - kenkensonson
    - YoshiakiYamasaki
    - gakumura
    - yoinakag
    - eminamin
    - TomokoKonishi
    - ora-takahnak
    - nonkyon
    - kyyamada
    - SNAKANE
    - yuarashi
    - s-nori
    - fwiw6430
    - kofukush
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - watarunS
    - ntakei1
    - unyako
    - t-utsunom
    - sogawa-yk
    - alkuma-san
  ".github/**":
    - tniita
    - mmarukaw
    - cyberblack28
    - nonkyon
    - sogawa-yk

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3
