apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: paasdocs-preview-ingress
  namespace: paasdocs-preview
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: paasdocs-preview-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - paasdocs'
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: paasdocs-preview
          servicePort: 80
        path: /
        pathType: Prefix
      - backend:
          serviceName: ocitutorials-preview
          servicePort: 4000
        path: /ocitutorials
        pathType: Prefix
      - backend:
          serviceName: ocidocs-preview
          servicePort: 4001
        path: /ocidocs
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
spec:
  selector:
    app: ocitutorials-preview
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
  labels:
    app: ocitutorials-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocitutorials-preview
  template:
    metadata:
      labels:
        app: ocitutorials-preview
    spec:
      containers:
      - name: ocitutorials-preview
        image: nrt.ocir.io/orasejapan/oci-tutorials/staging-env
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: paasdocs-preview-image-pull-secret
